### ISSUE TITLE
How could i change luaVersion for luaparse

### ISSUE THREAD

**Issue by SWSAmor** [trixnz/vscode-lua#11]
Usually I avoid goto, but today needed to use it and got this:
```message: 'unexpected identifier 'goto' near 'end'' at: '25,13' source: 'luaparse'```
so i think i should to set luaVersion for luaparse. How could i do that?
By the way i love your extension. 👍 Thx.

**Comment by trixnz** [comment]
Should be fixed in v0.7.0. There's now a version indicator in the bottom right of the window you can press. The change is persisted through your workspace settings.

**Comment by SWSAmor** [comment]
You are great, thank you.

**Comment by idevz** [comment]
I now using v0.12.4 still have this problem?

**Comment by SWSAmor** [comment]
It is working great. trixnz fixed that in July 2017.

**Comment by idevz** [comment]
@SWSAmor thk

**Comment by MRG95** [comment]
I'm also using v0.12.4 and getting this error. 
![Screenshot_329](https://user-images.githubusercontent.com/18136493/61490871-ea63ee80-a97b-11e9-93e1-e8b22b2d8961.png)

**Comment by BloodyRain2k** [comment]
I don't know why but I have this issue with 0.12.4 ![Image of the issue](https://drive.google.com/uc?id=1GioceLwr1jaB_vIBaqrDqSic7v8cozZK)

Interestingly do I have that same section of code twice due to being in the middle of refactoring, and while both were present it only found the first.
After that was gone into a raw code section [[ ]] it went over to complain about the second.

**Comment by SlightPersimmon1** [comment]
Still have the same issue with the latest vscode-lua (0.12.4)

<img width="1063" height="140" alt="Image" src="https://github.com/user-attachments/assets/6c0331f8-53fc-4397-ba21-35551d75ce59" />

I mean.. as a c and c# developer, i despise the "goto" command, but given that lua incentives it's usage (due the lack of proper cycle iteration skip), it shouldn't be a syntax error.
