### ISSUE TITLE
Empty luacheck path doesn't work

### ISSUE THREAD

**Issue by Nexela** [trixnz/vscode-lua#21]
luacheck is not ran if the luacheck path setting is empty  and the luacheck is on windows path. The second problem is the .bat extension is needed on it.

The default setting should be luacheck  (not null) and additionaly the code should add .bat behind the scenes if OS is windows

Something like this
```js
if (process.platform == 'win32' && path.extname(cmd) != '.bat') {
        cmd += '.bat'
    }
```

**Comment by trixnz** [comment]
The default behaviour for an empty path is to fail-early. It should definitely try the path first, though - I agree on that.

As for the Windows-specific `.bat` issue, I'm unable to test it right now as I'm on Linux. I welcome a PR, if you'd like to tackle it right now. Otherwise, I'll get this fixed next time I'm at a Windows env. 

Thanks for all the issues, by the way. Much appreciated! :smiley:
