### ISSUE TITLE
Luacheck no longer working on windows?

### ISSUE THREAD

**Issue by CyaNox** [trixnz/vscode-lua#41]
I had luacheck configured and working but since the past couple of days it refuses to work.

I have no idea how to check in vscode where if at all an extension is erroring.

I tried to get luacheck to bark with the following:
```lua
alskjdhlkajshd=nil;
ssss=defines;
sdfa=0;
```
But it is silent while it should have said something about each and everyone one of those lines.

These are my relevant settings (these worked perfectly):
```json
	"lua.luacheckPath": "D:/DEV/luacheck/luacheck.exe",
	"lua.preferLuaCheckErrors": true,
	"lua.targetVersion": "5.2",
```

**Comment by Nexela** [comment]
lintingservices.js:49  Possibly Should be:

  if (process.platform === 'win32' && path_1.extname(luacheckPath) == '' ) {
        luacheckPath += '.bat';
    }

Only append extension if extension isn't present,   Which leads to step 2,   Should it be "bat" or "exe"  Since luacheck has a windows binary now it is possible it should default to exe. 

Alternatively figuring out what it would take to run it without the extension at all would be best.

**Comment by trixnz** [comment]
luacheck has a binary release now? Awesome! I'll make the changes 😄.
